var telefonos = document.createElement("div");
telefonos.className = "cards_telefonos";
//Asistencia médica
var asistencia = document.createElement("div");
asistencia.className = "telefonos_card asistencia_card";
var asistenciaH3 = document.createElement("h3");
asistenciaH3.textContent = "Asistencia médica";
var asistenciaContent = document.createElement("div");
asistenciaContent.className = "telefonos_content";
var asistencialink1 = document.createElement("a");
asistencialink1.href = "https://wa.me/5491148729100";
var img1 = document.createElement("img");
img1.src = "https://osde-socios.grupoosdestatic.com.ar/hubfs/Telefono_Asistencia.svg";
var textNode1 = document.createTextNode("11.4872.9100");
asistencialink1.appendChild(img1);
asistencialink1.appendChild(textNode1);
asistenciaContent.appendChild(asistencialink1);
var asistencialink2 = document.createElement("a");
asistencialink2.href = "tel:08108887788";
var img2 = document.createElement("img");
img2.src = "https://osde-socios.grupoosdestatic.com.ar/hubfs/Tele%CC%81fono%20Asistencias.svg";
var textNode2 = document.createTextNode("0810.888.7788");
asistencialink2.appendChild(img2);
asistencialink2.appendChild(textNode2);
asistenciaContent.appendChild(asistencialink2);
var asistencialink3 = document.createElement("a");
asistencialink3.href = "tel:08109996300";
var img3 = document.createElement("img");
img3.src = "https://osde-socios.grupoosdestatic.com.ar/hubfs/Tele%CC%81fono%20Asistencias.svg";
var textNode3 = document.createTextNode("0810.999.6300");
asistencialink3.appendChild(img3);
asistencialink3.appendChild(textNode3);
asistenciaContent.appendChild(asistencialink3);
var asistencialink4 = document.createElement("a");
asistencialink4.href = "https://asistenciamedica.osde.com.ar/tabs/inicio";
asistencialink4.className = "solicitar_online";
asistencialink4.textContent = "Solicitar asistencia online";
asistenciaContent.appendChild(asistencialink4);
asistencia.appendChild(asistenciaH3);
asistencia.appendChild(asistenciaContent);
//Riesgo de vida
var riesgo = document.createElement("div");
riesgo.className = "telefonos_card riesgo_card";
var riesgoH3 = document.createElement("h3");
riesgoH3.textContent = "Riesgo de vida";
var riesgoContent = document.createElement("div");
riesgoContent.className = "telefonos_content";
var riesgoLink = document.createElement("a");
riesgoLink.href = "tel:08106661111";
var riesgoImg = document.createElement("img");
riesgoImg.src = "https://osde-socios.grupoosdestatic.com.ar/hubfs/Telefono_Riesgo.svg";
var riesgoText = document.createTextNode("0810.666.1111");
riesgoLink.appendChild(riesgoImg);
riesgoLink.appendChild(riesgoText);
riesgoContent.appendChild(riesgoLink);
riesgo.appendChild(riesgoH3);
riesgo.appendChild(riesgoContent);
//Atención al socio
var atencion = document.createElement("div");
atencion.className = "telefonos_card atencion_card";
var atencionH3 = document.createElement("h3");
atencionH3.textContent = "Atención al socio";
var atencionContent = document.createElement("div");
atencionContent.className = "telefonos_content";
var atencionHorarios = document.createElement("p");
atencionHorarios.textContent = "Lunes a viernes de 9 a 20 H";
var atencionLink1 = document.createElement("a");
atencionLink1.href = "https://wa.me/5491148729000";
var atencionImg1 = document.createElement("img");
atencionImg1.src = "https://osde-socios.grupoosdestatic.com.ar/hubfs/Whatsapp_Atencion.svg";
var atencionText1 = document.createTextNode("11.4872.9000");
atencionLink1.appendChild(atencionImg1);
atencionLink1.appendChild(atencionText1);
var atencionLink2 = document.createElement("a");
atencionLink2.href = "tel:08105556733";
var atencionImg2 = document.createElement("img");
atencionImg2.src = "https://osde-socios.grupoosdestatic.com.ar/hubfs/Telefono_Atencion.svg";
var atencionText2 = document.createTextNode("0810.555.6733");
atencionLink2.appendChild(atencionImg2);
atencionLink2.appendChild(atencionText2);
var atencionLink3 = document.createElement("a");
atencionLink3.href = "tel:08005556733";
var atencionImg3 = document.createElement("img");
atencionImg3.src = "https://osde-socios.grupoosdestatic.com.ar/hubfs/Telefono_Atencion.svg";
var atencionText3 = document.createTextNode("0800.555.6733");
atencionLink3.appendChild(atencionImg3);
atencionLink3.appendChild(atencionText3);
var atencionLink4 = document.createElement("a");
atencionLink4.href = "https://www.osde.com.ar/index.html#!osde-caps-centros-atencion-personalizada.html";
var img4 = document.createElement("img");
img4.src = "https://osde-socios.grupoosdestatic.com.ar/hubfs/Turnos.svg";
var atencionText4 = document.createTextNode("Turnos en sucursal");
atencionLink4.appendChild(img4);
atencionLink4.appendChild(atencionText4);
var atencionMail = document.createElement("p");
atencionMail.textContent = "contacto@osde.com.ar";
atencionContent.appendChild(atencionHorarios);
atencionContent.appendChild(atencionLink1);
atencionContent.appendChild(atencionLink2);
atencionContent.appendChild(atencionLink3);
atencionContent.appendChild(atencionLink4);
atencionContent.appendChild(atencionMail);
atencion.appendChild(atencionH3);
atencion.appendChild(atencionContent);

telefonos.appendChild(asistencia);
telefonos.appendChild(riesgo);
telefonos.appendChild(atencion);

//Falta agregarla en la estructura del footer que corresponda, mediante: _____.appendChild(telefonos);
//Para ver en VS: 
document.body.appendChild(telefonos);
